name: Swift

on:
  push:
    branches: [ master, feature/* ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install simulators
      run: xcversion simulators --install='iOS 15.4'
    - name: Build
      run: ./dev/build-project.sh
    - name: Run tests
      run: ./dev/run-tests.sh
